from django.urls import path
from .views import*

urlpatterns=[

    path("disciplines", disciplines, name="discipline/disciplines"),
    path("add-disc", add_disc, name="discipline/add_disc"),
    path("edit-disc/<str:id>", edit_disc, name="discipline/edit_disc"),
    path("edit-dis", edit_dis, name="discipline/edit_dis"),
    path("ajax_delete_discipline/<int:id>", ajax_delete_discipline, name="ajax_delete_discipline"),  
    path("del-disc/<str:id>", del_disc, name="del_disc"),

    path("composants", composants, name="composant/composants"),
    path("add-cmp", add_cmp, name="composant/add_cmp"),
    path("edit-cmp/<str:id>", edit_cmp, name="composant/edit_cmp"),
    path("edit-com", edit_com, name="composant/edit_com"),
    path("ajax_delete_multiple_composant/<int:id>", ajax_delete_multiple_composant, name="ajax_delete_multiple_composant"),  
    path("del-multiple_comp/<str:id>", del_multiple_cmp, name="del_multiple_cmp"),
    path("details_cmp/ajax_delete_composant/<int:id>", ajax_delete_composant, name="ajax_delete_composant"),  
    path("del-comp/<str:id>", del_cmp, name="del_cmp"),
    path("details_cmp/<str:id>", details_cmp, name="composant/details_cmp"),

    path("postquestion", postquestion, name="question/postquestion"),
    path("questions", questions, name="question/questions"),
    path("my-questions", my_questions, name="question/my_questions"),
    path("ajaxCompDisc/<int:id>", getCompDiscipline.as_view(), name="ajaxCompDisc"),
    path("del_ques/<int:id>", delquestion.as_view(), name="del_ques"),
    path("my_delques/<int:id>", my_delques.as_view(), name="my_delques"),
    path("detforum/f_delques/<int:id>", f_delques.as_view(), name="f_delques"),
    path("report-question/<int:id>", report_question, name="report_question"),
    path("report-lq/<int:id>", report_lq, name="report_lq"),
    path("report-quest", report_quest, name="report_quest"),
    path("cancel_quest_report/<int:id>", cancel_quest_report, name="cancel_quest_report"),
    path("cancel_ques_report/<int:id>", cancel_ques_report, name="cancel_ques_report"),

    path("answer/<str:id>", answer, name="question/answer"),
    path("f-answer/<str:id>", f_answer, name="question/f-answer"),
    path("my-answer/<str:id>", my_answer, name="question/my-answer"),
    path("answer/del_answer/<int:id>", delanswer.as_view(), name="del_answer"),
    path("my-answer/my_delanswer/<int:id>",my_delanswer.as_view(), name="my_delanswer"),
    path("f-delanswer/<int:id>",f_delanswer.as_view(), name="f-delanswer"),
    path("listforum", listforum, name="question/listforum"),
    path("detforum/<str:id>", detforum, name="question/detforum"),
    path("ajaxlike/<int:id>", ajaxlike.as_view(), name="ajaxlike"),
    path("ajaxlikes/<int:id>", ajaxlikes.as_view(), name="ajaxlikes"),
    path("answer/ajaxlike/<int:id>", ajaxlikeanswer.as_view(), name="ajaxlike"),
    path("answer/ajaxlikes/<int:id>", ajaxlikeanswers.as_view(), name="ajaxlikes"),
    path("f-answer/ajaxlike/<int:id>", ajaxlikeanswer.as_view(), name="ajaxlike"),
    path("f-answer/ajaxlikes/<int:id>", ajaxlikeanswers.as_view(), name="ajaxlikes"),
    path("my-answer/ajaxlike/<int:id>", ajaxlikeanswer.as_view(), name="ajaxlike"),
    path("my-answer/ajaxlikes/<int:id>", ajaxlikeanswers.as_view(), name="ajaxlikes"),
    path("detforum/ajaxlike/<int:id>", ajaxlike.as_view(), name="ajaxlike"),
    path("detforum/ajaxlikes/<int:id>", ajaxlikes.as_view(), name="ajaxlikes"),
    path("report-answer/<int:id>", report_answer, name="report_answer"),
    path("report-la/<int:id>", report_la, name="report_la"),
    path("report-answ", report_answ, name="report_answ"),
    path("cancel_answer_report/<int:id>", cancel_answer_report, name="cancel_answer_report"),
    path("cancel_answ_report/<int:id>", cancel_answ_report, name="cancel_answ_report"),
    
    path("count-report", count_report, name="question/count_report"),
    path("report-answers", report_answers, name="question/report_answers"),
    path("report-questions", report_questions, name="question/report_questions"),
    path("delete_rq/<int:id>", delete_rq.as_view(), name="delete_rq"),
    path("delete_ra/<int:id>", delete_ra.as_view(), name="delete_ra")
]
