# Generated by Django 5.0.7 on 2025-03-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0003_projet_devise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant_remboursement', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField()),
                ('date_contrat', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('Non commencé', 'Non commencé'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='Non commencé', max_length=20)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projet.projet')),
            ],
        ),
    ]
