# Generated by Django 5.0.7 on 2025-03-03 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_remboursement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_remboursement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('justification', models.TextField()),
                ('actionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contratremboursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='contrat.contratremboursement')),
            ],
        ),
    ]
