# Generated by Django 5.0.7 on 2025-03-05 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0003_signature_contrat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signature_contrat',
            new_name='SignatureContrat',
        ),
    ]
