# Generated by Django 5.0.7 on 2025-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0004_rename_signature_contrat_signaturecontrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursement',
            name='methode_paiement',
            field=models.CharField(choices=[('Virement bancaire', 'Virement bancaire'), ('PayPal', 'PayPal'), ('Espèces', 'Espèces'), ('Chèque', 'Chèque')], default='Espèces', max_length=20),
        ),
    ]
