# Generated by Django 5.0.7 on 2025-03-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0005_remboursement_methode_paiement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remboursement',
            old_name='methode_paiement',
            new_name='mode_paiement',
        ),
    ]
