# Generated by Django 5.0.7 on 2025-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0006_rename_methode_paiement_remboursement_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturecontrat',
            name='date_signature',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
