# Generated by Django 5.0.7 on 2025-03-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0007_alter_signaturecontrat_date_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturecontrat',
            name='contratremboursement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signaturecontrat', to='contrat.contratremboursement'),
        ),
    ]
