# Generated by Django 5.0.7 on 2025-03-06 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0008_alter_signaturecontrat_contratremboursement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturecontrat',
            name='contratremboursement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signaturecontrats', to='contrat.contratremboursement'),
        ),
        migrations.CreateModel(
            name='SignatureRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signature', models.DateField(auto_now_add=True, null=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('remboursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatureremboursements', to='contrat.remboursement')),
            ],
        ),
    ]
