# Generated by Django 4.1.6 on 2024-04-14 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_comp', models.CharField(choices=[('Langue', 'Langue'), ('Bureautique', 'Bureautique'), ("Système d'exploitation", "Système d'exploitation"), ('Logiciel', 'Logiciel'), ('Technologie web', 'Technologie web'), ('Langage de programmation', 'Langage de programmation'), ('Framework', 'Framework'), ('Système de Gestion de Base de Données', 'Système de Gestion de Base de Données'), ('Outil et Environnement', 'Outil et Environnement'), ('Modélisation', 'Modélisation'), ('Loisir', 'Loisir'), ('Data', 'Data')], max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
