# Generated by Django 5.0.7 on 2024-12-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='type_comp',
            field=models.CharField(choices=[('Langue', 'Langue'), ('Bureautique', 'Bureautique'), ("Système d'exploitation", "Système d'exploitation"), ('Logiciel', 'Logiciel'), ('Technologie web', 'Technologie web'), ('Langage de programmation', 'Langage de programmation'), ('Framework', 'Framework'), ('Système de Gestion de Base de Données', 'Système de Gestion de Base de Données'), ('Outil et Environnement', 'Outil et Environnement'), ('Modélisation', 'Modélisation'), ('Loisir', 'Loisir'), ('Data', 'Data'), ('Certification', 'Certification')], max_length=100),
        ),
    ]
