# Generated by Django 5.0.7 on 2026-07-04 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0003_typecompetence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='type_comp',
        ),
        migrations.AddField(
            model_name='competence',
            name='type_competence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competence.typecompetence'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
