# Generated by Django 5.0.7 on 2026-07-04 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0004_remove_competence_type_comp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='type_competence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competence.typecompetence'),
            preserve_default=False,
        ),
    ]
