from django.urls import path
from .views import*

urlpatterns=[
    path("cours", cours, name="cours/cours"),
    path("listcours", listcours, name="cours/listcours"),
    path("ajax_delete_cours_discipline/<int:id>", ajax_delete_cours_discipline, name="ajax_delete_cours_discipline"),  
    path("delete-cours-discipline/<str:id>", delete_cours_discipline, name="delete_cours_discipline"),
    path("detcours/<str:id>",detcours, name="cours/detcours"),
    path("detcours/ajax_delete_cours_composant/<int:id>", ajax_delete_cours_composant, name="ajax_delete_cours_composant"),  
    path("delete-cours-composant/<str:id>", delete_cours_composant, name="delete_cours_composant"),
    path("dcours/ajax_delete_cours/<int:id>", ajax_delete_cours, name="ajax_delete_cours"),  
    path("delete-cours/<str:id>", delete_cours, name="delete_cours"),
    path("dcours/<str:id>",dcours, name="cours/dcours"),
    path("v-cours/<str:id>",viewcours, name="cours/v-cours"),
    path("details/<str:id>", details, name="cours/details"),
    path("mescours", mescours, name="cours/mescours"),
    path("ajax_delete_document_discipline/<int:id>", ajax_delete_document_discipline, name="ajax_delete_document_discipline"),  
    path("delete-document-discipline/<str:id>", delete_document_discipline, name="delete_document_discipline"),
    path("d-cours/<str:id>", d_cours, name="cours/d-cours"),
    path("d-cours/ajax_delete_document_composant/<int:id>", ajax_delete_document_composant, name="ajax_delete_document_composant"),  
    path("delete-document-composant/<str:id>", delete_document_composant, name="delete_document_composant"),
    path("details-cours/<str:id>", details_cours, name="cours/details-cours"),
    path("details-cours/ajax_detail_document/<int:id>", ajax_detail_document, name="ajax_detail_document"),  
    path("details-cours/ajax_delete_document/<int:id>", ajax_delete_document, name="ajax_delete_document"),  
    path("delete-document/<str:id>/<str:code>", delete_document, name="delete_document"),
    path("add-cours", add_cours, name="cours/add_cours"),
    path("edit-cours/<str:id>", edit_cours, name="cours/edit_cours"),
    path("edit-cour", edit_cour, name="edit_cour"),
    path("doc-pur", doc_purchased, name="commande/doc-pur"),
    path("doc-cmd", doc_cmd, name="commande/doc-cmd"),
    path("my-docpur", my_doc_purchased, name="commande/my-docpur"),
    path("all-docpur", all_doc_purchased, name="commande/all-docpur"),
    path("purchase_month_year/<str:month_year>", purchase_month_year.as_view(), name="purchase_month_year"),
    path("purchase_month_year_user/<str:month_year_user>", purchase_month_year_user.as_view(), name="purchase_month_year_user"),

    path("mode-paye", mode_paiement, name="mode-paiement/mode-paye"),
    path("add-mode", add_mode, name="mode-paiement/add-mode"),
    path("edit-mode/<str:id>", edit_mode, name="mode-paiement/edit-mode"),
    path("edit-mod", edit_mod, name="mode-paiement/edit-mod"),
    path("ajax_delete_mode_payment/<int:id>", ajax_delete_mode_payment, name="ajax_delete_mode_payment"),
    path("del-mode/<str:id>", del_mode, name="mode-paiement/del-mode"),
    path("ajaxmode/<str:id>", ajaxmode.as_view(), name="ajaxmode"),
    path("edit-mode/ajaxmode/<str:id>", ajaxmode.as_view(), name="ajaxmode"),

    path("c-encours", coursencours, name="cours/c-encours"),
    path("dc-encours/<str:id>", detcoursencours, name="cours/detcoursencours"),
    path("d-encours/<str:id>", dcoursencours, name="cours/dcoursencours"),
    path("d-encours/ajax_detail_document_encours/<int:id>", ajax_detail_document_encours, name="ajax_detail_document_encours"),  

    path("cours-pub", courspub, name="cours/courspub"),
    path("detcourspub/<str:id>", detcourspub, name="cours/detcourspub"),
    path("dc-pub/<str:id>", dcourspub, name="cours/dcourspub"),
    path("dc-pub/ajax_detail_document_publie/<int:id>", ajax_detail_document_publie, name="ajax_detail_document_publie"),  

    path("c-nonpub", coursnonpub, name="cours/coursnonpub"),
    path("dc-nonpub/<str:id>", detcoursnonpub, name="cours/detcoursnonpub"),
    path("d-nonpub/<str:id>", dcoursnonpub, name="cours/dcoursnonpub"),
    path("d-nonpub/ajax_detail_document_nonpublie/<int:id>", ajax_detail_document_nonpublie, name="ajax_detail_document_nonpublie"),  

    path("ajaxCompDisc/<int:id>", getCompDiscipline.as_view(), name="ajaxCompDisc"),
    path("ajaxType/<str:id>", getPrice.as_view(), name="ajaxType"),
    path("edit-cours/ajaxType/<str:id>", getPrice.as_view(), name="ajaxType"),
    path("edit-cours/ajaxCompDisc/<int:id>", getCompDiscipline.as_view(), name="ajaxCompDisc"),
    path("ajaxCours/<int:id>", getCours.as_view(), name="ajaxCours"),

    path("addPanier/<int:id>", addPanier.as_view(), name="addPanier"),
    path("details/addPanier/<int:id>", addPanier.as_view(), name="addPanier"),
    path("panier", panier, name="commande/panier"),
    path("ajax_detail_cart/<int:id>", ajax_detail_cart, name="ajax_detail_cart"),
    path("ajax_delete_cart/<int:id>", ajax_delete_cart, name="ajax_delete_cart"),
    path("del-panier/<str:id>", del_panier, name="del_panier"),
    
    path("del-mode/<str:id>", del_mode, name="mode-paiement/del-mode"),
    path("md-paiement", md_paiement, name="commande/md_paiement"),
    path("paiement-paypal", paiement_paypal, name="commande/paiement_paypal"),
    path("payment-successful/<str:transaction_id>", payment_successful, name="commande/payment_successful"),
    path("validate-order", validate_order, name="commande/validate_order"),
    path("success", success, name="commande/success"),
    path("succ", succ, name="commande/succ"),
    path("echec", echec, name="commande/echec"),
    path("validation", validate, name="validation"),
    path('paiement_card_bancaire', paiement_card_bancaire, name='commande/paiement_card_bancaire'),
    path("commandes", commandes, name="commande/commandes"),
    path("det-cmd/<int:id>", det_cmd, name="commande/det-cmd"),
    path("achats", achats, name="commande/achats"),
    path("delachat/<int:id>", delachat, name="commande/delachat"),
    path("detachat/<int:id>", detachat, name="commande/detachat"),
    path("facture/<int:id>", facture, name="commande/facture"),
    path("paiement-mobile", paiement_mobile, name="commande/paiement_mobile"),
    
    path('update-payment-status/<str:transaction_id>/', update_payment_status, name='update_payment_status'),

    path("fetchdoccmp/<int:id>", fetchdoc.as_view(), name="fetchdoc"),
    path("detcours/fetchdoccmp/<int:id>", fetchdoccmp.as_view(), name="fetchdoccmp"),
    
    path("niveau/<str:id>", level.as_view(), name="niveau"),
    path("edit-cours/niveau/<str:id>", level.as_view(), name="niveau")
]