# Generated by Django 5.0.7 on 2025-02-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eajc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='devise',
        ),
    ]
