# Generated by Django 5.0.7 on 2025-02-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eajc', '0002_remove_setting_devise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='theme',
            field=models.CharField(choices=[('bg-gradient-primary', 'bg-gradient-primary'), ('bg-gradient-info', 'bg-gradient-info'), ('bg-gradient-success', 'bg-gradient-success'), ('bg-gradient-danger', 'bg-gradient-danger'), ('bg-gradient-warning', 'bg-gradient-warning'), ('bg-gradient-secondary', 'bg-gradient-secondary'), ('bg-gradient-dark', 'bg-gradient-dark')], max_length=200, null=True),
        ),
    ]
