# Generated by Django 5.0.7 on 2024-10-12 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annee', '0001_initial'),
        ('etablissement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baccalaureat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee1', models.IntegerField(default=0, null=True)),
                ('diplome', models.CharField(choices=[('BAC A1', 'BAC A1'), ('BAC A2', 'BAC A2'), ('BAC A3', 'BAC A3'), ('BAC A4', 'BAC A4'), ('BAC A5', 'BAC A5'), ('BAC C', 'BAC C'), ('BAC D', 'BAC D'), ('BAC E', 'BAC E'), ('BAC F1', 'BAC F1'), ('BAC F2', 'BAC F2'), ('BAC F3', 'BAC F3'), ('BAC F4', 'BAC F4'), ("BAC Français ('inscription non-règlementée')", "BAC Français ('inscription non-règlementée')"), ("BAC Français ('inscription règlementée')", "BAC Français ('inscription règlementée')"), ("BAC Français ('lycée français')", "BAC Français ('lycée français')"), ('BAC G1', 'BAC G1'), ('BAC G2', 'BAC G2'), ('BAC G3', 'BAC G3'), ('BAC R1', 'BAC R1'), ('BAC R2', 'BAC R2'), ('BAC R3', 'BAC R3'), ('BAC R4', 'BAC R4'), ('BAC R5', 'BAC R5'), ('BAC R6', 'BAC R6'), ('BAC R7', 'BAC R7'), ('Autre BAC', 'Autre BAC')], max_length=200, null=True)),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annee.annee')),
                ('etablissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etablissement.etablissement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
