# Generated by Django 5.0.7 on 2024-10-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baccalaureat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baccalaureat',
            name='annee1',
        ),
    ]
