# Generated by Django 5.0.7 on 2025-02-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0001_initial'),
        ('tache', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('type_depense', models.CharField(choices=[("Main d'œuvre", "Main d'œuvre"), ('Logiciel', 'Logiciel'), ('Matériel', 'Matériel'), ('Infrastructure', 'Infrastructure'), ('Autre', 'Autre')], max_length=50)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='projet.projet')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='tache.tache')),
            ],
        ),
    ]
