# Generated by Django 4.1.6 on 2024-04-05 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lettre_mot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('type', models.CharField(choices=[('Inscription', 'Inscription'), ('Stage', 'Stage'), ('Alternance', 'Alternance'), ('Emploi', 'Emploi')], max_length=100, null=True)),
                ('file', models.FileField(upload_to='upload')),
                ('statut', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
