# Generated by Django 4.1.6 on 2024-04-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettre_mot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettre_mot',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
