"""
Django settings for eajc project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
#eajc.mysql.pythonanywhere-services.com

from pathlib import Path
import os
import environ
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vmo@wosphuikcnl8i^02-lwgg^!-r@6@f3r!b3x#)_s_l^xp%%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    
    'daphne',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'eajc',
    'eab',
    'app_auth',
    'annee',
    'etablissement',
    'baccalaureat',
    'formation',
    'entreprise',
    'experience',
    'competence',
    'parcours',
    'forum',
    'document',
    'annonce',
    'reference',
    'lettre_mot',
    'chat',
    'portfolio',
    'ckeditor',
    'django_bootstrap_icons',
    'paypal.standard.ipn',
]

ASGI_APPLICATION = 'eajc.asgi.application'

# Configuration du backend de channel
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Ajoutez les paramètres de configuration de PayPal
PAYPAL_RECEIVER_EMAIL = 'sb-r1h34733654313@business.example.com'
PAYPAL_TEST = True  # Mettre à False en production

# Ajout des clés pour le compte stripe
#STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
#STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')

# Initialiser l'instance d'environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Maintenant, tu peux utiliser les variables d'environnement comme suit :
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY')

# Recuperer les clés primaire et secondaire de Momo
MTN_PRIMARY_KEY = env("MTN_PRIMARY_KEY")
MTN_SECONDARY_KEY = env("MTN_SECONDARY_KEY")

FERNET_KEY = 'eIEuhsiRkTuMQHd2pw5_MHJTXgj3aGD6Y6JPaa0XKaY='

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Notre middleware
    'eajc.middlewares.maintenance_middleware.MaintenanceMiddleware',  # Chemin vers le middleware
]

ROOT_URLCONF = 'eajc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eajc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'eab/static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT=os.path.join(BASE_DIR,'media/')
MEDIA_URL = '/media/'

#LOGIN_URL="/auth/login"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
#EMAIL_USE_SSL = False
EMAIL_PORT = 587
EMAIL_HOST_USER = 'eajccv@gmail.com'
EMAIL_HOST_PASSWORD = 'htpnbplhezawdpnb'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-warning',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.ERROR: 'alert-danger',
}


#Hebergement
#https://www.youtube.com/watch?v=ov6VzWwDy6M&t=91s
#https://www.youtube.com/watch?v=Okr2hjAO-78

#https://www.youtube.com/watch?v=sFPcd6myZrY

#https://www.youtube.com/watch?v=R4-XRK6NqMA (Websocket)