# Generated by Django 4.1.6 on 2023-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_remove_cours_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
