# Generated by Django 4.1.6 on 2023-05-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typepaiement', models.TextField(max_length=100)),
                ('numero', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
