# Generated by Django 4.1.6 on 2023-05-29 15:52

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_modepaiement_delete_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='modepaiement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='document.modepaiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='phone',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
