# Generated by Django 4.1.6 on 2023-05-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_commande_modepaiement_commande_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='modepaiement',
            name='libelle',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
