# Generated by Django 4.1.6 on 2023-05-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_modepaiement_libelle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modepaiement',
            old_name='numero',
            new_name='phone',
        ),
    ]
