# Generated by Django 4.1.6 on 2023-05-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_rename_numero_modepaiement_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modepaiement',
            old_name='phone',
            new_name='numero',
        ),
    ]
