# Generated by Django 4.1.6 on 2023-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_alter_commande_modepaiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='validation',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
