# Generated by Django 4.1.6 on 2023-05-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_alter_commande_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='validation',
            field=models.TextField(default='En cours de traitement ...', null=True),
        ),
    ]
