# Generated by Django 4.1.6 on 2023-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_alter_commande_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='comment',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='validation',
            field=models.IntegerField(default=0),
        ),
    ]
