# Generated by Django 5.0.7 on 2024-10-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='status_payment',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='commande',
            name='transaction_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='datecommande',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
