# Generated by Django 5.0.7 on 2024-10-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_commande_status_payment_commande_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='comment',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='phone',
            field=models.TextField(default='', max_length=100),
        ),
    ]
