# Generated by Django 5.0.7 on 2024-10-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_alter_commande_comment_alter_commande_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='validation',
            field=models.CharField(default='Commande en cours de traitement', max_length=30, null=True),
        ),
    ]
