# Generated by Django 5.0.7 on 2024-10-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_alter_commande_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='validation',
            field=models.CharField(choices=[('Commande en cours de traitement', 'Commande en cours de traitement'), ('Commande validée', 'Commande validée'), ('Commande non validée', 'Commande non validée')], default='Commande en cours de traitement', max_length=50, null=True),
        ),
    ]
