# Generated by Django 5.0.7 on 2024-11-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_alter_commande_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modepaiement',
            name='libelle',
            field=models.TextField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='numero',
            field=models.TextField(default='', max_length=100, null=True),
        ),
    ]
