# Generated by Django 4.1.6 on 2023-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0055_contact_statutdel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vaform',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Invisible', 'Invisible')], default='Visible', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vcomp',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Invisible', 'Invisible')], default='Visible', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vep',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Invisible', 'Invisible')], default='Visible', max_length=100, null=True),
        ),
    ]
