# Generated by Django 4.1.6 on 2023-06-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0056_profile_vp_alter_profile_vaform_alter_profile_vcomp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
