# Generated by Django 4.1.6 on 2024-03-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0062_alter_competence_type_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='type_exp',
            field=models.CharField(choices=[('Employé(e)', 'Employé(e)'), ('Stage', 'Stage'), ('Alternance', 'Alternance')], max_length=100),
        ),
    ]
