# Generated by Django 4.1.6 on 2024-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0063_alter_experience_type_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nature_recherche',
            field=models.TextField(null=True),
        ),
    ]
