# Generated by Django 4.1.6 on 2024-04-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0064_profile_nature_recherche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='niveau',
            field=models.CharField(choices=[('Baccalauréat', 'Baccalauréat'), ('Bac + 1', 'Bac + 1'), ('Bac + 2', 'Bac + 2'), ('Bac + 3', 'Bac + 3'), ('Bac + 4', 'Bac + 4'), ('Bac + 5', 'Bac + 5'), ('Bac + 6', 'Bac + 6'), ('Bac + 7', 'Bac + 7'), ('1ère année Ingénieur', '1ère année Ingénieur'), ('2ème année Ingénieur', '2ème année Ingénieur'), ('3ème année Ingénieur', '3ème année Ingénieur')], max_length=200, null=True),
        ),
    ]
