# Generated by Django 4.1.6 on 2024-04-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0065_alter_parcours_niveau'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='title',
            new_name='projet',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='projet_mission',
        ),
    ]
