# Generated by Django 4.1.6 on 2024-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0066_rename_title_experience_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vef',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Invisible', 'Invisible')], default='Visible', max_length=100, null=True),
        ),
    ]
