# Generated by Django 4.1.6 on 2024-04-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0067_profile_vef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='vef',
            new_name='vref',
        ),
    ]
