# Generated by Django 4.1.6 on 2024-04-12 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
        ('eab', '0068_rename_vef_profile_vref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etablissement.etablissement'),
        ),
        migrations.DeleteModel(
            name='Etablissement',
        ),
    ]
