# Generated by Django 4.1.6 on 2024-04-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_alter_reference_entreprise'),
        ('entreprise', '0001_initial'),
        ('formation', '0001_initial'),
        ('eab', '0069_alter_parcours_etablissement_delete_etablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='user',
        ),
        migrations.AlterField(
            model_name='experience',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formation.formation'),
        ),
        migrations.DeleteModel(
            name='Entreprise',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
    ]
