# Generated by Django 4.1.6 on 2024-04-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0070_remove_formation_user_alter_experience_entreprise_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
