# Generated by Django 4.1.6 on 2024-04-14 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0071_delete_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competence',
        ),
    ]
