# Generated by Django 4.1.6 on 2024-07-12 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0072_delete_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='datecontact',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.DeleteModel(
            name='Parcours',
        ),
    ]
