# Generated by Django 5.0.7 on 2024-10-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0073_alter_contact_datecontact_delete_parcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_deleteaccount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
