# Generated by Django 5.0.7 on 2024-10-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0074_profile_status_deleteaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='just_costumer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
