# Generated by Django 5.0.7 on 2024-12-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0075_profile_just_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
