# Generated by Django 5.0.7 on 2024-12-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0076_parametre_maintenance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
