# Generated by Django 5.0.7 on 2026-07-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0077_profile_linkedin_profile_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
