# Generated by Django 4.1.6 on 2023-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_remove_annonce_compagny_annonce_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='visibilty',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
