# Generated by Django 4.1.6 on 2023-05-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0003_annonce_visibilty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='visibilty',
            new_name='visibility',
        ),
    ]
