# Generated by Django 5.0.7 on 2025-07-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_settingsupuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='height_logo',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='width_logo',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='settingsupuser',
            name='height_logo',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='settingsupuser',
            name='width_logo',
            field=models.IntegerField(default=20),
        ),
    ]
