# Generated by Django 5.0.7 on 2025-07-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_setting_height_logo_alter_setting_width_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='height_logo',
            field=models.TextField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='width_logo',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='settingsupuser',
            name='height_logo',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='settingsupuser',
            name='width_logo',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
