# Generated by Django 5.0.7 on 2025-02-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Non commencé', 'Non commencé'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='Non commencé', max_length=20)),
                ('cout_estime', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cout_reel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projet.projet')),
            ],
        ),
    ]
