# Generated by Django 5.0.7 on 2025-02-10 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('type_projet', models.CharField(choices=[('Personnel', 'Personnel'), ('Individuel', 'Individuel'), ('En groupe', 'En groupe')], default='Personnel', max_length=20)),
                ('statut', models.CharField(choices=[('Planifié', 'Planifié'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='Planifié', max_length=20)),
                ('cout_estime', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cout_reel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
