# Generated by Django 5.0.7 on 2025-02-24 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devise', '0001_initial'),
        ('projet', '0002_projet_montant_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='devise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devise.devise'),
        ),
    ]
