# Generated by Django 5.0.7 on 2025-03-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_projet_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='visibilite_depense',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='visibilite_progres',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='visibilite_projet',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='visibilite_tache',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
