# Generated by Django 5.0.7 on 2024-12-27 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(null=True)),
                ('datecontact', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
    ]
