# Generated by Django 5.0.7 on 2024-12-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactportfolio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactportfolio',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
