# Generated by Django 5.0.7 on 2024-12-28 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_contactportfolio_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='These',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la thèse')),
                ('date_soutenance', models.DateField(verbose_name='Date de soutenance')),
                ('resume', models.TextField(blank=True, verbose_name='Résumé')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name="Titre de l'article")),
                ('resume', models.TextField(blank=True, verbose_name='Résumé')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('revue', models.CharField(blank=True, max_length=255, verbose_name='Revue/Conférence')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Volume')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Numéro')),
                ('pages', models.CharField(blank=True, max_length=50, verbose_name='Pages')),
                ('doi', models.CharField(blank=True, max_length=255, verbose_name='DOI')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='articles/', verbose_name='Fichier PDF')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='Lien URL')),
                ('keywords', models.TextField(blank=True, verbose_name='Mots-clés')),
                ('categorie', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('these', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='portfolio.these', verbose_name='Thèse associée')),
            ],
        ),
    ]
