# Generated by Django 5.0.7 on 2024-12-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_these_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='fichier',
            new_name='file',
        ),
    ]
