# Generated by Django 5.0.7 on 2024-12-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_fichier_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='these',
            name='universite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Université'),
        ),
    ]
