# Generated by Django 5.0.7 on 2025-02-13 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_progres', models.DateField(blank=True, null=True)),
                ('pourcentage', models.CharField(max_length=255)),
                ('commentaire', models.TextField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progres', to='projet.projet')),
            ],
        ),
    ]
