# Generated by Django 5.0.7 on 2025-02-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progres',
            name='pourcentage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
