# Generated by Django 5.0.7 on 2024-09-20 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagestatus_roomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='date_ac',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
