# Generated by Django 4.1.6 on 2024-03-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='nom',
            new_name='name',
        ),
    ]
