# Generated by Django 4.1.6 on 2024-03-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_reference_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
