# Generated by Django 4.1.6 on 2024-04-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
        ('reference', '0004_reference_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
    ]
