# Generated by Django 4.1.6 on 2024-04-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_experience_entreprise_alter_experience_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
