# Generated by Django 4.1.6 on 2024-04-13 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entreprise', '0001_initial'),
        ('experience', '0003_delete_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exp', models.CharField(choices=[('Employé(e)', 'Employé(e)'), ('Stage', 'Stage'), ('Alternance', 'Alternance')], max_length=100)),
                ('posteoccupe', models.CharField(max_length=200)),
                ('projet', models.CharField(max_length=200, null=True)),
                ('tache', models.CharField(max_length=300)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
