# Generated by Django 4.1.6 on 2024-06-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
        ('experience', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
    ]
