# Generated by Django 4.1.6 on 2024-06-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_alter_experience_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='posteoccupe',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
