# Generated by Django 4.1.6 on 2024-07-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_alter_experience_posteoccupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='lien',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
