# Generated by Django 5.0.7 on 2025-08-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_journalier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumejournanlier',
            name='date_resume',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
