# Generated by Django 5.0.7 on 2025-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_journalier', '0002_alter_resumejournanlier_date_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumejournanlier',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
