# Generated by Django 4.1.6 on 2024-04-14 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annee', '0001_initial'),
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee1', models.IntegerField(default=0, null=True)),
                ('niveau', models.CharField(choices=[('Baccalauréat', 'Baccalauréat'), ('Bac + 1', 'Bac + 1'), ('Bac + 2', 'Bac + 2'), ('Bac + 3', 'Bac + 3'), ('Bac + 4', 'Bac + 4'), ('Bac + 5', 'Bac + 5'), ('Bac + 6', 'Bac + 6'), ('Bac + 7', 'Bac + 7'), ('1ère année Ingénieur', '1ère année Ingénieur'), ('2ème année Ingénieur', '2ème année Ingénieur'), ('3ème année Ingénieur', '3ème année Ingénieur')], max_length=200, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('statusan', models.CharField(default='Non', max_length=50, null=True)),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annee.annee')),
                ('etablissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='etablissement.etablissement')),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='formation.formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
